# Generated by Django 5.2.17 on 2026-09-18 13:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='nome completo')),
                ('nascimento', models.DateField(verbose_name='data de nascimento')),
                ('telefone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9()+ \\-]{10,20}$', 'Informe um telefone válido com DDD.')])),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('especialidade', models.CharField(max_length=80)),
                ('registro', models.CharField(max_length=40, unique=True, verbose_name='registro profissional')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'profissionais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True, verbose_name='data da consulta')),
                ('inicio', models.TimeField(verbose_name='horário de início')),
                ('fim', models.TimeField(verbose_name='horário de término')),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('confirmada', 'Confirmada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada')], default='agendada', max_length=12)),
                ('observacoes', models.TextField(blank=True, help_text='Use apenas informações do agendamento, sem prontuário clínico.', max_length=1000, verbose_name='observações administrativas')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='consultas.paciente')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='consultas.profissional')),
            ],
            options={
                'verbose_name_plural': 'consultas',
                'ordering': ['data', 'inicio', 'pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('fim__gt', models.F('inicio'))), name='consulta_fim_apos_inicio')],
            },
        ),
    ]
